#!/bin/bash
#
# cloud-set-guest-password   Init file for Password Download Client
#
# chkconfig: 2345 98 02
# description: Init file for Password Download Client

### BEGIN INIT INFO
# Provides: cloud-set-guest-password
# Required-Start: $local_fs $network
# Required-Stop: $local_fs $syslog
# Should-Start: $syslog
# Should-Stop: $network $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Init file for Password Download Client
# Description:       Init file for Password Download Client
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

# Modify this line to specify the user (default is root)
user=root

# Add your DHCP lease folders here
DHCP_FOLDERS="/var/lib/dhclient/*"

function cloud_set_guest_password() {
    password_received=0
    file_count=0
    error_count=0

    for DHCP_FILE in $DHCP_FOLDERS; do
        if [ -f $DHCP_FILE ]; then
            file_count=$((file_count+1))
            PASSWORD_SERVER_IP=$(grep dhcp-server-identifier $DHCP_FILE | tail -1 | awk '{print $NF}' | tr -d '\;')

            if [ -n $PASSWORD_SERVER_IP ]; then
                logger -t "cloud" "Found password server IP $PASSWORD_SERVER_IP in $DHCP_FILE"
                logger -t "cloud" "Sending request to password server at $PASSWORD_SERVER_IP"
                password=$(wget -q -t 3 -T 20 -O - --header "DomU_Request: send_my_password" $PASSWORD_SERVER_IP:8080)
                password=$(echo $password | tr -d '\r')

                if [ $? -eq 0 ]; then
                    logger -t "cloud" "Got response from server at $PASSWORD_SERVER_IP"

                    case $password in
                    
                    "")					logger -t "cloud" "Password server at $PASSWORD_SERVER_IP did not have any password for the VM"
                                        continue
                                        ;;
                    
                    "bad_request")		logger -t "cloud" "VM sent an invalid request to password server at $PASSWORD_SERVER_IP"
                                        error_count=$((error_count+1))
                                        continue
                                        ;;
                                        
                    "saved_password") 	logger -t "cloud" "VM has already saved a password from the password server at $PASSWORD_SERVER_IP"
                                        continue
                                        ;;
                                        
                    *)					logger -t "cloud" "VM got a valid password from server at $PASSWORD_SERVER_IP"
                                        password_received=1
                                        break
                                        ;;
                                        
                    esac
                else
                    logger -t "cloud" "Failed to send request to password server at $PASSWORD_SERVER_IP"
                    error_count=$((error_count+1))
                fi
            else
                logger -t "cloud" "Could not find password server IP in $DHCP_FILE"
                error_count=$((error_count+1))
            fi
        fi
    done

    if [ "$password_received" == "0" ]; then
        if [ "$error_count" == "$file_count" ]; then
            logger -t "cloud" "Failed to get password from any server"
            exit 1
        else
            logger -t "cloud" "Did not need to change password."
            exit 0
        fi
    fi

    logger -t "cloud" "Changing password ..."
    echo $password | passwd --stdin $user
                            
    if [ $? -gt 0 ]; then
        logger -t "cloud" "Failed to change password for user $user"
    fi

    logger -t "cloud" "Successfully changed password for user $user"
    logger -t "cloud" "Sending acknowledgment to password server at $PASSWORD_SERVER_IP"
    wget -t 3 -T 20 -O - --header "DomU_Request: saved_password" $PASSWORD_SERVER_IP:8080
}

# See how we were called.
case "$1" in
  start)
    action $"Starting cloud-set-guest-password: " /bin/true
    cloud_set_guest_password
    RETVAL=$?
    ;;
  stop)
    action $"Shutting down cloud-set-guest-password: " /bin/true
    RETVAL=$?
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *) 
    echo $"Usage: cloud-set-guest-sshey {start}"
    RETVAL=2
    ;;
esac

exit $RETVAL
