#!/bin/sh
#
# Init file for SSH Public Keys Download Client
#
# chkconfig: 345 98 02
# description: SSH Public Keys Download Client

### BEGIN INIT INFO
# Provides: cloud-set-guest-sshkey
# Required-Start: $network $syslog $local_fs
# Required-Stop: $network $syslog $local_fs
# Default-Start: 3 5
# Default-Stop: 0 1 2 6
# Short-Description: SSH Public Keys Download Client
# Description: CloudStack SSH Public Keys Download Client
### END INIT INFO

# Modify this line to specify the user (default is root)
user=root

# Add your DHCP lease files here
DHCP_FILES="/var/lib/dhcpcd/*.leases"

keys_received=0
file_count=0

for DHCP_FILE in $DHCP_FILES; do
	if [ -f $DHCP_FILE ]; then
		file_count=$((file_count+1))
        source $DHCP_FILE
		SSHKEY_SERVER_IP=$DHCPSIADDR

		if [ -n $SSHKEY_SERVER_IP ]; then
			logger -t "cloud" "Sending request to ssh key server at $SSHKEY_SERVER_IP"

			publickey=$(wget -t 3 -T 20 -O - http://$SSHKEY_SERVER_IP/latest/public-keys 2>/dev/null)

			if [ $? -eq 0 ]; then
				logger -t "cloud" "Got response from server at $SSHKEY_SERVER_IP"
				keys_received=1
				break
			fi
		else
			logger -t "cloud" "Could not find ssh key server IP in $DHCP_FILE"
		fi
	fi
done

# did we find the keys anywhere?
if [ "$keys_received" == "0" ]; then
    logger -t "cloud" "Failed to get ssh keys from any server"
    exit 1
fi

# set ssh public key
homedir=$(grep ^$user /etc/passwd|awk -F ":" '{print $6}')
sshdir=$homedir/.ssh
authorized=$sshdir/authorized_keys

if [ ! -e $sshdir ]; then
    mkdir $sshdir
fi

if [ ! -e $authorized ]; then
    touch $authorized
fi

#cat $authorized|grep -v "$publickey" > $authorized
#echo "$publickey" >> $authorized
#To support user copied ssh keys
if [ `grep -c "$publickey" $authorized` == 0 ]; then
        echo "$publickey" >> $authorized
fi

exit 0
