#!/bin/sh
#
# cloudpasswd:
#  Allows resetting root password
#  via LeaseWeb Self Service Center

# PROVIDE: cloudpasswd
# REQUIRE: LOGIN NETWORKING cleanvar
# KEYWORD: shutdown

. /etc/rc.subr
name="cloudpasswd"
command="/usr/local/sbin/cloudpasswd"
rcvar=cloudpasswd_enable
load_rc_config "${name}"
run_rc_command "$1"

