#!/bin/sh

if [ "$reason" != BOUND ] && [ "$reason" != RENEW ] && [ "$reason" != REBIND ] && [ "$reason" != REBOOT ]; then
    return
fi

# set hostname
current_hostname=$(/bin/hostname)
if [ x$current_hostname = x ] || [ x$current_hostname = x$old_host_name ]; then
  if [ x$current_hostname = x ] || [ x$new_host_name != x$old_host_name ]; then
    $LOGGER "New Hostname: $new_host_name"
    hostname $new_host_name
  fi
fi
