#!/bin/sh
#
# Init file for Password Reset Client for FreeBSD
#
# chkconfig: 345 98 02
# description: Password Reset Client

# Modify this line to specify the user (default is root)
user=root

# Add your DHCP lease files here
DHCP_FILES="/var/db/dhclient.leases.*"
WGET=/usr/local/bin/wget
LOG=/usr/bin/logger

valip() {
    echo $1 | /usr/bin/grep -Eq '^(25[0-5]|2[0-4][0-9]|[0-1]{1}[0-9]{2}|[1-9]{1}[0-9]{1}|[1-9])\.(25[0-5]|2[0-4][0-9]|[0-1]{1}[0-9]{2}|[1-9]{1}[0-9]{1}|[1-9]|0)\.(25[0-5]|2[0-4][0-9]|[0-1]{1}[0-9]{2}|[1-9]{1}[0-9]{1}|[1-9]|0)\.(25[0-5]|2[0-4][0-9]|[0-1]{1}[0-9]{2}|[1-9]{1}[0-9]{1}|[0-9])'
}
password_received=0
file_count=0
error_count=0

for DHCP_FILE in $DHCP_FILES; do
  if [ -f $DHCP_FILE ]; then
    file_count=$((file_count+1))
    maxcheck=15
    ip="$(awk -F ' |;' '/dhcp-server-identifier/ { print $5 }' ${DHCP_FILE} | tail -1)"
    ipcheck=0
    until valip ${ip}; do
      [ $ipcheck -eq $maxcheck ] && continue 2
      sleep 3
      ${LOG} -t "cloud-passwd" "No valid IP \"${ip}\" found in ${DHCP_FILE}"
      ip="$(awk -F ' |;' '/dhcp-server-identifier/ { print $5 }' ${DHCP_FILE} | tail -1)"
      ipcheck=$((ipcheck+1))
    done
    PASSWORD_SERVER_IP=$ip
    if [ -n $PASSWORD_SERVER_IP ]; then
      ${LOG} -t "cloud-passwd" "Found password server IP \"${PASSWORD_SERVER_IP}\" in \"${DHCP_FILE}\""
      ${LOG} -t "cloud-passwd" "Sending request to password server at \"${PASSWORD_SERVER_IP}\""
      password=$(${WGET} -q -t 3 -T 20 -O - --header "DomU_Request: send_my_password" $PASSWORD_SERVER_IP:8080)
      passcheck=0
      until [ $? -ne 4 ]; do
        [ $passcheck -eq $maxcheck ] && continue 2
        sleep 3
        ${LOG} -t "cloud-passwd" "Wget exited with exit code $?, retrying"
        password=$(${WGET} -q -t 3 -T 20 -O - --header "DomU_Request: send_my_password" $PASSWORD_SERVER_IP:8080)
        passcheck=$((passcheck+1))
      done
      password=$(echo $password | tr -d '\r')

      if [ $? -eq 0 ]; then
        ${LOG} -t "cloud-passwd" "Got response from server at $PASSWORD_SERVER_IP"
        case $password in
          "")
            ${LOG} -t "cloud-passwd" "Password server at $PASSWORD_SERVER_IP did not have any password for the VM"
            continue
            ;;
          "bad_request")
            ${LOG} -t "cloud-passwd" "VM sent an invalid request to password server at $PASSWORD_SERVER_IP"
            error_count=$((error_count+1))
            continue
            ;;
          "saved_password")
            ${LOG} -t "cloud-passwd" "VM has already saved a password from the password server at $PASSWORD_SERVER_IP"
            continue
            ;;
          *)
            ${LOG} -t "cloud-passwd" "VM got a valid password from server at $PASSWORD_SERVER_IP"
            password_received=1
            break
            ;;
        esac
      else
        ${LOG} -t "cloud-passwd" "Failed to send request to password server at $PASSWORD_SERVER_IP"
        error_count=$((error_count+1))
      fi
    else
      ${LOG} -t "cloud-passwd" "Could not find password server IP in $DHCP_FILE"
      error_count=$((error_count+1))
    fi
  fi
done

if [ "$password_received" == "0" ]; then
  if [ "$error_count" == "$file_count" ]; then
    ${LOG} -t "cloud-passwd" "Failed to get password from any server"
    exit 1
  else
    ${LOG} -t "cloud-passwd" "Did not need to change password."
    exit 0
  fi
fi

${LOG} -t "cloud-passwd" "Changing password ..."
echo $password | pw mod user $user -h 0

if [ $? -gt 0 ]; then
  echo "${password}" | /usr/sbin/pw usermod -u 0 -h 0 2>/dev/null
  if [ $? -gt 0 ]; then
    ${LOG} -t "cloud-passwd" "Failed to change password for user $user"
    exit 1
  fi
else
  ${LOG} -t "cloud-passwd" "Successfully changed password for user $user"
fi

# Plesk password change if the /etc/psa folder is an existing directory
[ -d /etc/psa/ ] && PSA_PASSWORD=$password /usr/local/psa/admin/bin/ch_admin_passwd > /dev/null 2>&1

${LOG} -t "cloud-passwd" "Sending acknowledgment to password server at $PASSWORD_SERVER_IP"
${WGET} -t 3 -T 20 -q -O /dev/null --header "DomU_Request: saved_password" $PASSWORD_SERVER_IP:8080
exit 0
